apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: disabled
  settings.yaml: |
    title: 72602 Homepage
    theme: gray
    description: A Monitoring Dashboard for All Services in 72602
    startUrl: /
    discovery:
      enabled: false
    hideVersion: true
    disableUpdateCheck: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google
    layout:
      Developer:
        style: row
        columns: 5
      Blog:
        style: row
        columns: 5
      Media:
        iconsOnly: true
      Tool:
        iconsOnly: true
  bookmarks.yaml: |
    - Blog:
        - DEV-BLOG:
            - abbr: ay's dev blog
              icon: https://raw.githubusercontent.com/AaronYang0628/home-site/refs/heads/main/static/icons/dev_blog.png
              href: https://aaronyang0628.github.io/docs/
        - WZ-BLOG:
            - abbr: wangzhi
              icon: blogger
              href: https://blog.geekcity.tech/articles/
        - BK-BLOG:
            - abbr: cnconti
              icon: blogger
              href: https://memo.cnconti.tech/#/
    - Developer:
        - AY's Github:
            - abbr: GH
              icon: github
              href: https://github.com/AaronYang0628
        - Aliyun:
            - abbr: Ali
              icon: aliyun
              href: https://home.console.aliyun.com/home/dashboard/ProductAndService
        - OperatorHub:
            - abbr: OSH
              icon: https://raw.githubusercontent.com/AaronYang0628/home-site/refs/heads/main/static/icons/operator_hub.png
              href: https://operatorhub.io/
        - Artifacthub:
            - abbr: AH
              icon: artifacthub
              href: https://artifacthub.io/
        - ACR:
            - abbr: ACR
              icon: docker-engine
              href: https://cr.console.aliyun.com/cn-hongkong/instance/dashboard
    - Tool:
        - ChatGPT:
            - abbr: chatgpt
              icon: chatgpt
              href: https://chatgpt.com/
        - Doubao:
            - abbr: DB
              icon: https://raw.githubusercontent.com/AaronYang0628/home-site/refs/heads/main/static/icons/doubao.png
              href: https://www.doubao.com/chat/
        - Deepseek:
            - abbr: DB
              icon: deepseek
              href: https://chat.deepseek.com/
        - Emojipedia:
            - abbr: emoji
              icon: https://raw.githubusercontent.com/AaronYang0628/home-site/refs/heads/main/static/icons/dev_blog.png
              href: https://emojipedia.org/
        - Gemini:
            - abbr: GM
              icon: google-gemini
              href: https://gemini.google.com/
        - Claude Code:
            - abbr: Claude
              icon: claude-ai
              href: https://claude.ai/new
        - FontAwesome:
            - abbr: FA
              icon: fontawesome
              href: https://fontawesome.com/v6/search?o=r
        - Skywork:
            - abbr: SKY
              icon: google-slides
              href: https://skywork.ai/
        - ICON:
            - abbr: IC
              icon: dashboard-icons-dark
              href: https://dashboardicons.com/
        - PayWallBuster:
            - abbr: PWB
              icon: google-chrome
              href: https://paywallbuster.com/
    - Media:
        - Twitter:
            - abbr: twitter
              icon: twitter
              href: https://x.com/
        - RedBook:
            - abbr: XHS
              icon: si-xiaohongshu
              href: https://www.xiaohongshu.com/explore
        - YouTube:
            - abbr: YT
              icon: youtube
              href: https://youtube.com/
        - Bilibili:
            - abbr: BB
              icon: bilibili
              href: https://bilibili.com/
        - IYF:
            - abbr: IYF
              icon: nowshowing
              href: https://www.iyf.tv/?from=1
  services.yaml: |
    - Proxy Service:
        - Proxy[Bridge + Service] At ECS:
            icon: traefik-proxy
            href: http://server.proxy.72602.online
            description: GoProxy Bridge At ECS
            siteMonitor: http://server.proxy.72602.online
        - Proxy[Client] At 72602:
            icon: haproxy
            href: http://client.proxy.72602.online
            description: GoProxy Client At 72602 Home
            siteMonitor: http://client.proxy.72602.online
        - SSH At 72602:
            icon: terminal
            ping: 47.110.67.161
            description: SSH Service At 72602 Home
    - Basic Components:
        - Minio Ingress:
            href: https://console.minio.72602.online
            icon: minio
            description: https://console.minio.72602.online
            siteMonitor: https://console.minio.72602.online
        - Mariadb Ingress:
            href: https://mariadb.72602.online
            icon: mariadb
            description: https://mariadb.72602.online
            siteMonitor: https://mariadb.72602.online
        - Postgres Ingress:
            icon: postgres
            href: https://postgres.72602.online
            description: https://postgres.72602.online
            siteMonitor: https://postgres.72602.online
        - Redis Ingress:
            icon: redis
            href: https://redis.72602.online
            description: https://redis.72602.online
            siteMonitor: https://redis.72602.online
        - N8N Ingress:
            icon: n8n
            href: https://n8n.72602.online
            description: https://n8n.72602.online
            siteMonitor: https://n8n.72602.online
        - ArgoCD At 72602:
            icon: argo-cd
            description: ArgoCD Monitor
            href: https://argo-cd.72602.online
            siteMonitor: https://argo-cd.72602.online
            widget:
              type: argocd
              url: https://argo-cd.72602.online
              key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJyZWFkb25seTphcGlLZXkiLCJuYmYiOjE3NjIxNTk4ODMsImlhdCI6MTc2MjE1OTg4MywianRpIjoiNDljMmM2OTQtYTcwMy00Y2QwLWE0ZGEtOWQzMzI1YTRkNTg5In0.hIBqtzYb5SzkzommfZF8doq8Nm14c2_XMhH6IcTTPgw
              insecure: true
    - App Or DEMO:
        - Port Blog Ingress:
            href: http://port.72602.online
            icon: hugo
            description: http://port.72602.online
            siteMonitor: http://port.72602.online
        - RAG DEMO Ingress:
            href: http://rag.demo.72602.online
            icon: nginx
            description: http://rag.demo.72602.online
            siteMonitor: http://rag.demo.72602.online
        - Agent DEMO Ingress:
            href: http://agent.demo.72602.online
            icon: nginx
            description: http://agent.demo.72602.online
            siteMonitor: http://agent.demo.72602.online
    - Conatiners: []
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
    - logo:
        href: http://home.72602.online
        target: _blank 
        icon: https://raw.githubusercontent.com/AaronYang0628/home-site/refs/heads/main/static/icons/st_icon_alpha.png
  docker.yaml: ""
  custom.css: ""
  custom.js: ""